### PR TITLE
OSD feature ...

### PR DESCRIPTION
**Pull request by nik0**
- Add OSD display
- Add text font generator

### CODE REVIEW

**Comment by iashwinprasada** [comment]
@nik0 can you also consider implementing IVS-Move feature from the encoder? I'm trying to implement that by reading the sample file [here](https://github.com/dim08/Ingenic-T10_20/blob/master/samples/libimp-samples/sample-Encoder-h264-IVS-move.c). 

We could use the result from this and read it from an external program to record motion videos

**Comment by nik0** [comment]
@iashwinprasada,
It was my first plan to implement the built-in movement detection.  I tried it, but I have some crashes (https://github.com/EliasKotlyar/Xiaomi-Dafang-Software/issues/4)
My planB was to compile motion/ffmpeg on the Camera. I did succeed, but ffmpeg crashed at execution.
So I moved to planC to use my Raspberry to monitor my camera :-)

**Comment by iashwinprasada** [comment]
Yeah! I faced the same issue, but the thing is, even directly running from the [sample file](https://github.com/dim08/Ingenic-T10_20/blob/master/samples/libimp-samples/sample-Encoder-h264-IVS-move.c)   has a similar behaviour, we must be missing something. 

btw, how are ypu motinoring for motion from rpi using rtsp stream? what software?

**Comment by nik0** [comment]
Yes I use the rtsp stream with motion. I made a script that is triggered at detection to send me an email ... I works fine for my cameras

**Pull request merged**
